### ISSUE TITLE
undefined: pnet.Protector

### ISSUE THREAD

**Issue by maoxs2** [libp2p/go-libp2p-transport-upgrader#50]
Env: go 1.14 win

Probelm:
```cmd
# github.com/libp2p/go-libp2p-transport-upgrader
..\..\go\pkg\mod\github.com\libp2p\go-libp2p-transport-upgrader@v0.1.1\upgrader.go:29:12: undefined: pnet.Protector
```

Why github.com/libp2p/go-libp2p-transport-upgrader
```cmd
> go mod why github.com/libp2p/go-libp2p-transport-upgrader
# github.com/libp2p/go-libp2p-transport-upgrader
github.com/ngin-network/ngcore/ngp2p
github.com/libp2p/go-libp2p
github.com/libp2p/go-libp2p-circuit
github.com/libp2p/go-libp2p-transport-upgrader
```

in go.mod
```
	github.com/libp2p/go-libp2p v0.5.2
```

and then I checked [godoc](https://godoc.org/github.com/libp2p/go-libp2p-core/pnet), there does not have `pnet.Protector` type.

**Comment by marten-seemann** [comment]
`pnet.Protector` was recently removed, please upgrade to https://github.com/libp2p/go-libp2p-transport-upgrader/releases/tag/v0.2.0.
See https://github.com/libp2p/go-libp2p/releases/tag/v0.6.0.

**Comment by maoxs2** [comment]
Thanks, it's fixed after upgrading to`github.com/libp2p/go-libp2p v0.6.0`
